#---------------------------
# Material-T
# Author: rook1e
# Github: https://github.com/0x2e/Material-T
#---------------------------

#---------------------------
# 全局
# Site
#---------------------------
favicon: /favicon.ico
title_join_string: ' ~ '  # 浏览器标签页中的标题分隔符，效果： 文章名 ~ 站点名
highlight:
  enable: true
  theme: tomorrow-night-eighties  # available: github-v2 | tomorrow | tomorrow-night | tomorrow-night-eighties , you can download more from https://jmblog.github.io/color-themes-for-google-code-prettify/ then save `*.min.css` in `source/lib/prettify`
fun_features:
  typing: # 为 subtitle 添加打字机效果
    enable: true
    typeSpeed: 70 # 打印速度
    cursorChar: "" # 游标字符
    loop: false # 是否循环播放效果
  anchorjs: # 为文章内容中的标题添加锚图标
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right # icon放置的位置： left | right
    visible: false # true：一直可见，false：鼠标悬停时出现
    icon: "" # 例如：§ | # | ❡ 等，留空则为默认效果
baidu_analytics:  # 百度统计的Key

#---------------------------
# 导航栏
# Head Navbar
#---------------------------
navbar:
  menu:
    Home: /
    # Archives: /archives/
    # About: /about/

#---------------------------
# 页脚
# Footer
#---------------------------
footer:
  beian:  # The footer of China's website policy, other areas keep disable
    enable: false
    icp_text:  # ICP证号
    police_text:  # 公安备案号，不填则只显示ICP
    police_code:  # 公安备案的编号，用于URL跳转查询

#---------------------------
# 首页
# Index Page
#---------------------------
index: 
  banner_img: /bg.jpeg
  banner_img_height: 100  # available: 0 - 100
  slogan:  # 首页副标题的独立设置
    enable: true  # 为 false 则不显示任何内容
    text:  # 为空则使用 config.subtitle
  auto_excerpt:
    enable: true
    length: 300
  post_url_target: _self  # available: _blank | _self
  post_info:
    enable: true


#---------------------------
# 文章页
# Post Page
#---------------------------
post: 
  banner_img: /bg.jpeg
  banner_img_height: 70  # available: 0 - 100
  toc: 
    enable: true
  highlight:
    enable: true
    theme: tomorrow-night-eighties # available: github | tomorrow | tomorrow-night | tomorrow-night-eighties
  copyright:
    enable: false
    content: 日常笔记记录
  comments: 
    enable: false
    type: disqus  # available: disqus | valine
  date_format: "dddd, MMMM Do YYYY, h:mm a"
  custom:
    enable: false
    content: '<img src="" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">' # 自定义区域，支持 HTML，可自行插入赞赏码、公众号二维码等内容


# Disqus
disqus:
  shortname: # your shortname

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false # When enable is set to be true, leancloud_visitors is recommended to be closed for the re-initialization problem within different leancloud adk version.
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: 说点什么 # comment box placeholder
  avatar: retro # gravatar style https://valine.js.org/avatar.html
  pageSize: 10 # pagination size
  visitor: false # leancloud-counter-security is not supported for now. When visitor is set to be true, appid and appkey are recommended to be the same as leancloud_visitors' for counter compatibility. Article reading statistic https://valine.js.org/visitor.html


#---------------------------
# 归档页
# Archive Page
#---------------------------
archive: 
  banner_img: /bg.jpeg
  banner_img_height: 80  # available: 0 - 100

#---------------------------
# 关于页
# About Page
#---------------------------
about:
  banner_img: /bg.jpeg
  banner_img_height: 80  # available: 0 - 100
  avatar: 
  name: ThoughtZer
  introduce: info / info / info
  icons: 
    github: https://github.com